name = "macabre_gleeunit"
version = "1.11.0"
licences = ["Apache-2.0"]
description = "A simple test runner for Gleam (macabre python-target fork of gleeunit)"
repository = { type = "github", user = "dusty-phillips", repo = "macabre_gleeunit" }
links = [{ title = "Sponsor", href = "https://github.com/sponsors/lpil" }]
gleam = ">= 1.13.0"

[javascript.deno]
allow_read = ["gleam.toml", "test", "build"]

[dependencies]
gleam_stdlib = ">= 1.0.0 and < 2.0.0"
macabre_stdlib = { git = "git@github.com:dusty-phillips/macabre_stdlib.git", ref = "main" }

[dev-dependencies]
testhelper = { "path" = "./testhelper" }
